# 这是整个应用的配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_shop
    # 数据库连接
    username: root
    password: My82952620
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # 邮件配置（可选，如果不配置则邮件功能不会启用）
  mail:
    host: smtp.qq.com  # 邮件服务器地址
    port: 587
    username: 2304969186@qq.com  # 发送邮件的邮箱
    password: danaxniheksseahi # 邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    from: 2304969186@qq.com  # 默认发送邮箱

server:
  port: 1414  # 服务器端口

mybatis:
  mapper-locations: classpath:com.fourteen.mapper/*.xml
  type-aliases-package: com.fourteen.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名映射开关
    map-underscore-to-camel-case: true