# 这是整个应用的配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_shop
    # 数据库连接
    username: root
    password: My82952620
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 1414  # 服务器端口

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名映射开关
    map-underscore-to-camel-case: true
